### ISSUE TITLE
Multiple Y axis, domain changing,  

### ISSUE THREAD

**Issue by Pinxie** [rrag/react-stockcharts#35] opened 2015-11-24 17:43 UTC
Hello !

I'm currently using react-stockcharts for a big professional projet to display data sent via WebSocket. I particulary need LineSeries, and I am working with DataSeries. I'm fairly new to Javascript (and thus D3JS,  React) programming, and i have some questions:

- Is it possible to fix the maximum / minimum ticks values for an axis? I currently have a dirty workaround, which is to return undefined when the value exceeds my limit. It isn't great because if I don't get a value thas is close to the limit, my Y axis won't display this limit (except if I construct a fake point to reach this limit).

Here I want my Y axis to be limited to the value 10 :
yAccessor={(d) => d["value"] > 10? undefined : d["value"]}

- Is there a clean way to display several Y axis ? I know that you can put one on each side, and I also tried to specify a number a pixels, for example YAxis axisAt=40 orient="right" ticks={2}, but the problem is that it overlaps the Chart and its curves.

- I can have Time based data that are related to each other, (for example, displaying the tweets per minutes about individuals), but I want several X axis (so I can compare the TPM about Justin Bieber during the 25th December, and the TPM about Celine Dion during the 3rd May). Unfortunately, I have an xAccessor on the Chart with multiple DataSeries to specify yAccessor but not the other way around. I had some ideas to bypass this problem by making one Chart per X axis, repeating the Y axis for each Chart, and hiding all of them except one. Is there an other way to proceed?

I hope I was not confusing, English is not my native language.

Thanks.

**Comment by rrag** [comment] 2015-11-24 19:00
RE:
> Is it possible to fix the maximum / minimum ticks values for an axis? ...

when you say
> Y axis to be limited to the value 10 :

what do you want to see on the chart when there is an item which has a larger value?

RE:
> Is there a clean way to display several Y axis ?...

I am not following why the `axisAt` is not good, you could set it at different pixel values, [here](http://plnkr.co/edit/GNFnZHexakBDudnrwTV5?p=preview) is an example with multiple yaxis all on the right side. does this help?

RE:
> I can have Time based data that are related to each other...

So I understand what you are asking, you want to be able to see the yValue of 3rd May and 25th Dec for 2 different `yAccessor`, sort of like shifting the xAxis of one series so you can match up with another series?

**Comment by Pinxie** [comment] 2015-11-24 19:33
Wow thanks for the fast reply

> what do you want to see on the chart when there is an item which has a larger value? 

I want the user to guess there are higher value items (the curve increases up to the limit) to eventually  decrease back to a visible item.

>I am not following why the axisAt is not good, you could set it at different pixel values, here is an >example with multiple yaxis all on the right side. does this help?

Yes exactly, I don't know why I must have messed it up, thanks. I tried to put them on the left side, maybe it is related? I need to test that again

>So I understand what you are asking, you want to be able to see the yValue of 3rd May and 25th >Dec for 2 different yAccessor, sort of like shifting the xAxis of one series so you can match up with >another series?

Exactly ! To see the variations between 2 set of datas that occured at different times.

**Comment by rrag** [comment] 2015-11-24 20:08
RE:
>Is it possible to fix the maximum / minimum ticks values for an axis? ...

That should be possible by creating a custom indicator, and provide a `domain` with the min and max value that you need. A little bit more of coding, needed to override the default behavior which will fit the max and min values of all the `yAccessor`s in that `Chart`. An example would be the RSI series, where the domain always has to be between 0 and 100.

https://github.com/rrag/react-stockcharts/blob/master/src/lib/indicator/RSIIndicator.js#L71-L73

there is some [documentation](http://rrag.github.io/react-stockcharts/documentation.html#/custom_create_indicator) on how to create custom indicators. If you still have trouble with this, I will be happy to help.

RE:
> I can have Time based data that are related to each other...

That is not possible, but I wonder how what you say will be helpful?

I can understand if say you want to compare the number of houses sold by month, over 5 years, and you want each year to be a different series, you will compare
Jan 2010 with Jan 2011 and Jan 2012 ...
Feb 2010 with Feb 2011 ... 

what you explain is different, I have not seen any charts which does that. any examples in the wild, so I can better understand how that visualization will be helpful.

Though not what you are asking, have you considered using the `CompareSeries` instead? it would give you a % increase over time.

**Comment by Pinxie** [comment] 2015-11-25 23:29
>what you explain is different, I have not seen any charts which does that. any examples in the wild, so I can better understand how that visualization will be helpful.

Yep, I havn't seen such examples either, but the users will need that. For example, being able to compare sales in December between any other month that don't include Christmas. 
I have tested to put 2 X axis, one on the top and one at the bottom, but after enabling Zoom with:

<EventCapture mouseMove={true} zoom={true} pan={true} mainChart={1} defaultFocus={false} />

the others X axis seem to be copies of the X axis of the mainChart, when focusing the graph. I have reproduced this problem [here] (http://plnkr.co/edit/P917KwQImKxVAyWnAy8x?p=preview) .



When focusing the graph, the problem occurs.

I had an other trouble that I could'nt reproduce with this plunker, it's that when I focus the graph, the graph disappears (and there are no console errors, unfortunately). I suspect that's because my array of data can be incomplete (I can have a different number of points for each curves, so the points at the end of the array can be undefined), do you have any idea ? I don't think I messed up with the mainChart Id. 

An other question, I don't understand why, when removing the following line from [here](http://plnkr.co/edit/GNFnZHexakBDudnrwTV5?p=preview)	
	
dataTransform={[ { transform: StockscaleTransformer } ]}

The ChartCanvas disappears. Why is the transformation needed here? 

Thanks.

**Comment by rrag** [comment] 2015-11-26 12:00
> the others X axis seem to be copies of the X axis of the mainChart, when focusing the graph. I have reproduced this problem here .

each `Chart` has a pair of scales `xScale` & `yScale` currently all the `Charts` will share copies of the same `xScale` and these scales are calculated on zoom, pan, and a few other actions. So when you zoom or pan here, the scales are recomputed and both `Chart`s get the same `xScales` this is expected behavior. However I am looking to create a different type of chart where the `xScale` can be computed for each chart, for something like volume profile, but even that wont fit your need of shifting the same data

> I had an other trouble that I could'nt reproduce with this plunker, it's that when I focus the graph, the graph disappears

onmousedown => panStart is triggered
onmouseup => panEnd is triggered

onpanend recalculates the scales for the data you are currently seeing on screen, I am not sure what the problem is, without seeing it on a plunker. I am happy to help if you provide a plunker or point me to a public repo with the issue.

> An other question, I don't understand why, when removing the following line from here

stockscale is explained [here](http://rrag.github.io/react-stockcharts/documentation.html#/candlestick_chart) if you remove the stockscale each `Chart` needs an `xAccessor`, Stockscale provides the `xAccessor` implicitly, to all its children, if you see your AreaChart example earlier, that does not have stockscale but has an `xAccessor` on each `Chart`.

This needs a better error message to be logged on console.

**Comment by Pinxie** [comment] 2015-11-30 00:15
>it's that when I focus the graph, the graph disappears



> stockscale is explained here if you remove the stockscale each Chart needs an xAccessor, 

Well, silly me, thanks.

Is there somewhere you explain how to "build" your git repo? Because I have no idea how to do it, "npm install" just seem to download all source code & dependency, but I wonder how to "build" the sources (under /lib) once I modify them into dist/react-stockchart.js ... Because what i'm doing now is modifying react-stockchart.js, but it feels really bad (especially when I want to do an other Indicator...) 

One question I should have asked earlier : how do I use stockcharts to display asynchronous data? I managed to kind of do it, but it feels clumsy to me. 

![plotjsarray1](https://cloud.githubusercontent.com/assets/15984761/11460975/84a57d18-96f9-11e5-8aa7-52a41ae45abc.png)

I want 3 curves, one for each type of Y (ep1value, ep2value ep3value).
As you can see, I have "valueX" as my timestamp and "ep1value", "ep2value", "ep3value" my Ys for my 3 yAccessors. to each valueX there are at least one "epXvalue".

The first problem I have with that, it's I have to tell, for each yAccessor, wether or not it has an Y:
For example, here would be the accessor for my curve representing ep1value :

`yAccessor = {"ep1Value" in d? d["ep1Value"] : undefined}`


The second problem, Is that when a point undefined, the "pencil is lifted", the curve is "cut". I just had to modify Line.js drawOnCanvas to avoid interrupting the drawing : 

`if (yAccessor(d) === undefined) {
			return ;
}`

I am not sure it is the proper way to do, is there a way to assign to each yAccessor its own array? 

The third problem, is if I want each epXValue to have their own Y axis, I didn't manage to it any other way than giving each yAccessor its own Chart, but it poses multiple problems, such as zoom, X axis not being the same...

**Comment by rrag** [comment] 2015-11-30 16:51
Based the way you have structured the data, can you confirm if this is true?


index | valueX | ep1ValueY | ep2ValueY | ep3ValueY
------- | -------- | -------------- | -------------- | -------------- 
rawData[0]| Jan 01 1970 00:00:00 |  |  | 0
rawData[1]| Jan 01 1970 00:00:30 | somevalue |  | 
rawData[2]| Jan 01 1970 00:01:00 |  | somevalue | 
rawData[3]| Jan 01 1970 00:01:30 |  |  | 0.008
rawData[4]| Jan 01 1970 00:02:00 | somevalue | | 
rawData[5]| Jan 01 1970 00:02:30 | | somevalue | 
rawData[6]| Jan 01 1970 00:03:00 | | | somevalue  

in other words, is your data for say ep3ValueY not continuous? but has gaps?

> Is there somewhere you explain how to "build" your git repo?

refer to [CONTRIBUTING.md](https://github.com/rrag/react-stockcharts/blob/master/CONTRIBUTING.md)

Also for creating a custom series, you don't *need* to start from the stockcharts codebase, you could create then as part of your app and then include it.

Closing this issue as these are not issues I see with the library, but general questions, I am happy to continue the discussion here or even better in the gitter chatroom.

**Closed by rrag** 2015-11-30 16:51 UTC

**Comment by Pinxie** [comment] 2015-11-30 20:30
> in other words, is your data for say ep3ValueY not continuous? but has gaps?

Yes. this is due to the fact that datas have milliseconds precision, and different gaps between 2 values (one data can have one value every 20 milliseconds, an other data will have a value every 10 seconds, etc. ). Ideally, I would have done one array of arrays, with each array representing all the values (x,y) of one curve, because there is a low probability that I will know the Y of more than one curve for an X.

> open http://localhost:8090 in a browser

That's probably what I missed, I suppose the javascript builds itself inside /dist only if i do this step. I'm not used to this kind of thing :)

> Also for creating a custom series

Yes, I did just that for the custom indicator for fixing the domain, it works perfectly, thanks ! 

> the gitter chatroom. 

Well I'm a github newbie too, couldn't find a link to your chatroom, I would be interested !

**Comment by rrag** [comment] 2015-11-30 20:49
https://gitter.im/rrag/react-stockcharts
