### ISSUE TITLE
Support Inferno

### ISSUE THREAD

**Issue by stevesouth** [rrag/react-stockcharts#231] opened 2017-02-22 16:33 UTC
Given that a lot of js execution time is spent in react it would be interesting to see what performance gains could be achieved by using inferno / inferno-compat, but it doesn't seem to work out of the box.

Interestingly preact / preact-compat does work, so it is likely to be an inferno bug rather than an issues with react-stockcharts. I'll try and speak to @trueadm.

**Comment by degroote22** [comment] 2017-02-24 03:08
The issue is because of [this function](https://github.com/rrag/react-stockcharts/blob/master/src/lib/utils/ChartDataUtil.js#L46), at least on my tests.
What happens is that this function is called on the lifecycle method componentWillMount of the first component of the tree. It assumes that the children passed props will be merged onto their defaultProps, which on Inferno is not the case.
Discussion is going on the Inferno side towards this. If this project would like to support Inferno as is then it should stop assuming that defaultProps would be merged onto the children props before the component has been mounted.

**Comment by rrag** [comment] 2017-02-24 03:26
excellent troubleshooting. I need the child props of `Chart` from the parent. Is there a better way to achieve  this?

I could easily solve this problem I guess by merging myself with `Chart.defaultProps`, but looking for a better elegant solution if one exists

**Comment by rrag** [comment] 2017-02-24 06:31
@stevesouth attempted a fix in `next` branch. hopefully it fixes this (fingerscrosed)

**Comment by stevesouth** [comment] 2017-02-24 09:51
The chart loads now, but on pan the chart disappears and i'm seeing:

Uncaught (in promise) TypeError: Cannot read property '_unmounted' of null : inferno.node line 1411

**Comment by degroote22** [comment] 2017-02-24 10:59
I'll take a look on it on a couple of days. I'm going to travel today and upon arrival I'll try to do it.

**Comment by trueadm** [comment] 2017-02-24 13:49
In regards to handling of `defaultProps`, this differs between React and Inferno in that Inferno lazily tries to handle merging `props` with `defaultProps` when dealing with the component, React does this when creating the `ReactElement`, introducing a performance penalty that we wanted to avoid with Inferno. I believe the plan is to change the implementation to fall in line with how React handles `defaultProps`

It would be awesome if someone could throw up a repo with the `next` branch, an example using `inferno-compat` so I can clone locally and investigate. :) 

Thanks for all the work investigating this issue!

**Comment by degroote22** [comment] 2017-02-26 21:48
The fix to the defaultProps issue has landed on Inferno on version 1.3.0-rc8

**Comment by rrag** [comment] 2017-02-27 12:32
Thank you @degroote22 for the follow up. I have a busy week ahead and will not be able to get to this for now. I will create new branch with inferno resolve alias as suggested by @trueadm later.

Thank you for looking into this and your work on inferno.

**Closed** 2017-07-24 04:45 UTC
