### ISSUE TITLE
Enable/Disable Zoom

### ISSUE THREAD

**Issue by shprink** [rrag/react-stockcharts#163] opened 2016-11-04 09:38 UTC
Hi,

I saw that you removed `EventCapture` https://github.com/rrag/react-stockcharts/blob/78bbf30e4e29580aceedbc0e6fe0c8829b95b88b/docs/md/CHANGE-LOG.md

Is there any way now to enable/disable the zoom on demand? The problem being when you scroll down a page and happen to be on top of a chart then it starts zooming instead of scrolling. We want to have a button to enable chart interaction instead of having it by default.

Thanks, we <3 your lib :)

**Comment by rrag** [comment] 2016-11-04 10:43
it is not possible to disable pan/zoom in `0.6-beta` 
It has to be added. If you are interested in doing a PR, I can guide you on what needs to be done.

Closing - Duplicate of https://github.com/rrag/react-stockcharts/issues/161

**Closed by rrag** 2016-11-04 10:43 UTC

**Comment by shprink** [comment] 2016-11-04 12:38
Yep, we are interested in helping. Please let me know the details of what you have in mind for the implementation (new props? HOC? new component?)

thanks

**Comment by rrag** [comment] 2016-11-04 14:10
Great here is what I am thinking

in `ChartCanvas.jsx`

```diff
class ChartCanvas extends Component {
	...
	...
	render() {
		...
		...
		<EventCapture
-			mouseMove={interaction}
+			mouseMove={!disableMouseMoveEvent && interaction}
-			zoom={interaction}
+			zoom={!disableMouseMoveEvent && interaction}
-			pan={interaction && !drawMode}
+			pan={!disableMouseMoveEvent && interaction && !drawMode}

			width={dimensions.width}
			height={dimensions.height}
			chartConfig={chartConfig}
			xScale={xScale}
		...
	}
}

ChartCanvas.propTypes = {
	width: PropTypes.number.isRequired,
	height: PropTypes.number.isRequired,
	...
	...
+	disableMouseMoveEvent: PropTypes.bool.isRequired,
+	disablePanEvent: PropTypes.bool.isRequired,
+	disableZoomEvent: PropTypes.bool.isRequired,
	onSelect: PropTypes.func,
};

ChartCanvas.defaultProps = {
	...
	defaultFocus: true,
	onLoadMore: noop,
	onSelect: noop,
	// ratio: 2,
+	disableMouseMoveEvent: false,
+	disablePanEvent: false,
+	disableZoomEvent: false,
};
```

and then when you use it in your component
```jsx

handleSelect() {
	this.setState({ focus: true })
}

render() {
	...
	var focus = this.state.focus;
	...
	return (<ChartCanvas
		disableMouseMoveEvent={focus}
		disablePanEvent={focus}
		onSelect={this.handleSelect}
		...
		...>
		...
		...
	</ChartCanvas>
```

Refer [CONTRIBUTING.md](https://github.com/rrag/react-stockcharts/blob/master/CONTRIBUTING.md) on how you can test your changes

Change any of the charts in https://github.com/rrag/react-stockcharts/tree/master/docs/lib/charts to test your changes.

I always use

https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/CandleStickChartWithEdge.jsx

to play with my experiments before it becomes an example on its own

**Comment by johnreytanquinco** [comment] 2018-10-17 08:16
I tried to add the values from https://github.com/rrag/react-stockcharts/blob/master/docs/md/ZOOM-AND-PAN.md in the ChartCanvas. It works on chart display but not in the Y-axis label. How can I fully disable the mouse and scroll events in both chart and the label section?

My result is the same if we add the following props in ChartCanvas in https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithCompare

```
return (
	<ChartCanvas height={400}
		mouseMoveEvent={false}
		panEvent={false}
		zoomEvent={false}
		clamp={false}
        ...
```
Actual result when I drag the Y-axis.
![screenshot from 2018-10-17 16-14-42](https://user-images.githubusercontent.com/7284893/47072092-e279f100-d227-11e8-900e-5d4fa32f7ed9.png)

**Comment by johnreytanquinco** [comment] 2018-10-17 08:36
Okay, I think this is the solution im looking for. https://github.com/rrag/react-stockcharts/pull/164#issuecomment-259113522
>look at zoomEnabled prop in XAxis, YAxis in CandleStickChartWithZoomPan.jsx
