### ISSUE TITLE
Width and Spacing of Minute Candlesticks

### ISSUE THREAD

**Issue by colorwheeloflife** [rrag/react-stockcharts#519] opened 2018-03-28 16:57 UTC
Hello

So we are implementing the candlestick chart with resolution options that include 15min and 30min.  When rendering, the candlesticks appear very skinny and spaced apart.  We would like them to render close to how the rest of the chart does. 

Here is the react-stockcharts chart with 15min resolution over 2 weeks:
![screen shot 2018-03-28 at 9 44 30 am](https://user-images.githubusercontent.com/10913613/38043917-2b85a368-326d-11e8-9299-9ddae95f5087.png)

Here is trading view's chart also with 15min resolution over 2 weeks:
![screen shot 2018-03-28 at 9 45 02 am](https://user-images.githubusercontent.com/10913613/38043942-3afc7eb6-326d-11e8-98f9-8182e7e6f180.png)

Here is react-stockcharts chart with 1 hour resolution over 1 week:
![screen shot 2018-03-28 at 9 47 01 am](https://user-images.githubusercontent.com/10913613/38043972-4ef1aa40-326d-11e8-9f76-b188c8e847f2.png)

Additionally, here is the first react-stockcharts with 15min resolution when zoomed up:
![screen shot 2018-03-28 at 9 50 45 am](https://user-images.githubusercontent.com/10913613/38044051-8472fec6-326d-11e8-960b-95383ea98dae.png)

Lastly, here is the react-stockcharts with 1hour resolution when zoomed up:
![screen shot 2018-03-28 at 9 53 34 am](https://user-images.githubusercontent.com/10913613/38044207-f85071d4-326d-11e8-97b5-05ab893fceed.png)

Note how spaced out the bars are from one another in the minutes chart opposed to the hour chart. 

I am currently changing the resolutions by interchanging 'utcMinute', 'utcHour', and 'utcDay' from the d3-time package into the 'timeIntervalBarWidth' function that is passed to the width property CandlestickSeries component.

When I tried to access this 'timeIntervalBarWidth' my edits to the function did not make it to the browser. 

How do you suggest making the minute candlesticks look more appropriate for the context?

Thank you

**Comment by rrag** [comment] 2018-03-28 18:56
I recall this issue, it was with the 
> When I tried to access this 'timeIntervalBarWidth' my edits to the function did not make it to the browser.

what does this mean your edits did not make it to the browser?

can you change to use `plotDataLengthBarWidth` and see if that helps?
I don't recall why `timeIntervalBarWidth` was added.

**Comment by colorwheeloflife** [comment] 2018-03-28 20:47
Okay.  The `timeIntervalBarWidth` was handy for switching back and forth between resolution types, but yes, does not seem complete.  

It is still active in your first candlestick example.  You seemed to have taken a different approach in the second example. 

I am now getting an error with `plotDataLengthBarWidth` 
> Uncaught TypeError: accessor is not a function


Here is what I am passing it:
```
import { utcMinute } from "d3-time";

const xScaleProvider = discontinuousTimeScaleProvider
    .inputDateAccessor(d => d.date);
const {
  data,
  xScale,
  xAccessor,
  displayXAccessor,
} = xScaleProvider(initialData);

const moreProps = {
  xScale,
  xAccessor,
  plotData: data_back
};

<CandlestickSeries width={ plotDataLengthBarWidth(utcMinute, moreProps) }/>
```


I meant by.. 

> When I tried to access this 'timeIntervalBarWidth' my edits to the function did not make it to the browser.

..is that when I tried to add a debugger/console logs they were ignored.  Not sure why or how that was the case.

**Comment by rrag** [comment] 2018-03-28 22:08
can you try
```jsx
<CandlestickSeries />
```

**Comment by colorwheeloflife** [comment] 2018-03-28 22:50
not including `width` breaks everything

**Comment by rrag** [comment] 2018-03-28 23:07
I dont know what the problem is, do you have a few mins to chat about this on gitter?

**Comment by colorwheeloflife** [comment] 2018-03-28 23:16
Sure.  Just messaged you on there.

**Comment by rrag** [comment] 2018-04-08 02:37
Closing as @colorwheeloflife got this working

**Closed by rrag** 2018-04-08 02:37 UTC

**Comment by khkwan0** [comment] 2018-06-27 01:20
was there a fix to this issue?  i'm having the same problem

**Comment by MaxYari** [comment] 2019-10-30 11:45
Oh, I love it so much when the issue got fixed but no solution is posted.

**Comment by rm-rf-etc** [comment] 2020-05-01 11:12
Wow, nobody even bothers to reply. Thanks so much.

**Comment by MaxYari** [comment] 2020-05-01 11:30
I think this is an issue about bar width not automatically adjusting on different time frames, right? (I'm too lazy rn to read it through :3 ) if so:

@rm-rf-etc and for anyone interested - I have no clue how to make this calculate proper sizing automatically again but for my use case I've simply made a dict of d3 timeframes like that:
```
import { utcDay, utcMinute, utcHour } from "d3-time";

periodToTimeIntervalMap: {
	"1m": utcMinute,
	"5m": utcMinute.every(5),
	"30m": utcMinute.every(30),
	"1h": utcHour,
	"3h": utcHour.every(3),
	"1d": utcDay
},
```
And then provided appropriate one to `CandlestickSeries`'s `width` property as `timeIntervalBarWidth(timeInterval)`.

Well, in fact, I have a proxy/accessor that also allows me to adjust bar width returned by `timeIntervalBarWidth` to achieve a slight gap between bars:

```
function barWidthAccessor(widthMult) {
	return function() {
		return widthMult*timeIntervalBarWidth(timeInterval)(...arguments);
	}				
};
```
And then use it like:
```
<CandlestickSeries	
	...						
	width={barWidthAccessor(0.8)}/>
```

Would've been better if this all worked automagically, but it's better than nothing. Hope this helps :)

**Comment by svv2014** [comment] 2021-03-03 03:23
Wasn't easy to find even after reading all ... so leaving last message what worked for me 

` <CandlestickSeries width={timeIntervalBarWidth(utcMinute.every(1))}/> `
