### ISSUE TITLE
Pan limits

### ISSUE THREAD

**Issue by moon47usaco** [rrag/react-stockcharts#151] opened 2016-10-03 21:20 UTC
Can you set the limit of the pan so that it does not go past the chart data or only goes past by a defined value? Currently in the Zoom & Pan demo ( http://rrag.github.io/react-stockcharts/documentation.html#/zoom_and_pan ) you can pan right past all the data leaving a blank chart.

Is there a way to limit the amount it can go past the last data point and set it to not ever go before the first data point?

Say 10-20 bars past the last bar and never before the first bar.

**Comment by rrag** [comment] 2016-10-03 21:22
dupe of https://github.com/rrag/react-stockcharts/issues/123 fixed in `next` branch

The pan/zoom limit is not configurable. You need a minimum of 2 datapoints on a chart, so you cannot go before the first 2, and go after the last 2

**Closed** 2016-10-13 00:11 UTC

**Comment by khaphannm** [comment] 2020-10-19 03:41
@moon47usaco did u come up with a solution for that ?
