### ISSUE TITLE
Avoid useless re-renders with componentShouldUpdate or PureComponents

### ISSUE THREAD

**Issue by Rafkraft** [rrag/react-stockcharts#216] opened 2017-02-02 12:56 UTC
hey Ragu

I'm using react-stockcharts in a professionnal project. I recently dived into source code to understand why some components got re-rendered uselessely and understood why.

Have you considered using react's shouldComponentUpdate method to optimize performances ? It allows you to rigorously determine when your component should render again by comparing actual props and new props.

For example, axes/YAxis has no shouldComponentUpdateMethod, and gets re-rendered everytime, even if the props did not change ! That's not good at all. To fix this, we can implement a shouldComponentUpdate method or simply `extends PureComponent` instead of `extend Component`.

This has to be done in few components of the lib. I think i can handle this, do you want me to create PR for these improvements ??

Raf

**Comment by rrag** [comment] 2017-02-02 23:53
There should not be any useless renders. Can you explain how I can reproduce that problem?

I would rather fix the root problem than add sCU. There are right now only a very few sCU/extends PureComponent used in the lib, and I plan to remove them also. Also with fiber coming sCU is considered to be just a hint is not guaranteed to prevent an update

**Comment by Rafkraft** [comment] 2017-02-03 14:43
Hey thanks for answering !

I had a deeper look into the lib, and I noticed that in `ChartCanvas#componentWillReceiveProps`, you are populating `context` with **a lot** of data, that are later recovered in some branch / leaf components (`lib/axes/YAxis`, `genericChartComponent`, `GenericComponent` and I guess many other).

I understand the philosophy of doing this way; having access to every `chartConfig` and other stuff from everywhere, and no need to bother passing it through `props` everytime. But this is not a right usage of `context`, context must be used only for general config/other data, and must not be updated through time, or very very meticulously.

## Some general react thoughts, and the situation here:
At each step, components should know if calling their render method is necessary by comparing `nextProps` and `props`, if some lower-level / leaf components depend on `context` for rendering, **any** `shouldComponentUpdate` **returning false in any n-parent will stop the render propagation**, and the lower-level / leaf component won't get updated. **This is exactly the situation here**, that's why we must not implement `PureComponents` or `shouldComponentUpdate` methods, because context might have changed, and lower-hierarchy components depend on context.

This massively-context-based way of coding prevent components from intelligently stopping propagation when its considered useless (props did not change), if such logic could be implemented in `react-stockchart`, I think it could drasticly improve its performances (Some components like `YAxis` almost never change over time, they should not get re-rendered when props are the same).

## The right way to do, I think
Get completely rid of context, **pass everything that the children need through** `props`, sometime it can get verbose, especially in high-order components like `ChartCanvas`, but this definitively improves clarity of the code, coherence of data-flow, and general performance for sure.


Did I miss something in the lib ? Do you agree ?

**Comment by rrag** [comment] 2017-02-03 15:16
> context must be used only for general config/other data, and must not be updated through time

I don't agree with this statement. While I would like to avoid context, the reason for that is because the api is not documented and could possibly change in future versions. redux, react-router also use context to pass on updates through time.

There is no other better alternative I am aware of. Passing via props is not an option as the owner component does not have access to the config on initial render and also on subsequent renders of mousemove or pan/zoom the owner component does not get the chart config.

The axis does need to get updated, when there is a pan, the yaxis ticks change to reflect the domain of the data. x axis ticks also, on mousemove there is no need for the axis to be updated and it is not, that is addressed by not updating the state of `ChartCanvas` during mousemove. `ChartCanvas` state is updated only on zoom, pan end, and in `ChartCanvas#componentWillReceiveProps`. I was initially updating the state on pan actions also but that led to performance issues, so now pan skips the `ChartCanvas` state update.

for. e.g when there is a mousemove event, the `CandleStickSeries` or `XAxis` does not need to be rendered again, that is avoided not by having a sCU on these components, but by using some listeners which get called from `GenericComponent`

I still don't quite understand where you are seeing double renders or avoidable renders.

As for improving performance, it is already pretty good, but [here](https://github.com/rrag/react-stockcharts/issues/206#issuecomment-275550088) is what I think can still be done to improve it. I will be surprised to find any measurable improvement, but you can never be sure till that is implemented.

I have been thinking about using a props based approach eliminating context completely, but that will be nothing like the current api. Will have to invest some time to do a prototype with that. If you are interested in creating such an api, I will be happy to share my ideas on that.

**Comment by Rafkraft** [comment] 2017-02-06 15:18
Hi !

Thanks for your answer, I'm working on a jsfiddle (or else) demo to highlight the useless renders I'm talking about.

**Comment by Rafkraft** [comment] 2017-02-07 09:29
Hey

So here's a simple demo, working with last RSC, I hard-copied RSC.js in my html file so I can put log in some of the components'render/else functions.

http://www.filedropper.com/rsc-example

Open the file in your brower, it's a simple chart that gets re-rendered every second **with exact same props.** You'll se that every components get re-rendered, canvas get re-drawn...

In a perf-optimized react-app, XAxis, YAxis, and particularly LineSeries should not be re-rendered when given same props, and especially LineSeries#drawOnCanvas wich is a very gourmande operation.

My code is from line 31190

**Comment by rrag** [comment] 2017-02-07 14:45
Thank you for this, I understand it better now.

I initially understood the problem as there are avoidable, when the chart is working like, on mousemove there are things that are rendered which don't have to be.

In this case the solution to avoid useless render is on the userland, where `RCSPerfRenderChecker` should have a `sCU/extends PureComponent`. having every component extend PureComponent is not a good idea, it could technically be less performant (although hard to measure) due to these checks which happen very often on pan/zoom. Lets assume there are XXXSeries or other components which become available from others, it is a reasonable expectation that all the different folks who create these and distribute would implement `scu` instead doing this on the owner component means there is only one check and the whole tree is not rendered.

Thank you for the patience and trying to explain the problem,  Reading this issue again I feel, I should have understood this earlier as I already have this optimization in an app I am building.

**Closed** 2017-02-13 16:29 UTC
