### ISSUE TITLE
Is it possible to highlight zones in Canvas?

### ISSUE THREAD

**Issue by li-huo** [rrag/react-stockcharts#210] opened 2017-01-18 13:25 UTC
Hi there,
I was wondering if react-stockchart supports zone hightlighting? for example.
![image](https://cloud.githubusercontent.com/assets/17079439/22065736/83ebe7dc-ddc4-11e6-9b95-65ae7d61a3ac.png)

I try to achieve this with 'Annotation', but it seems like the annotation object can only be text / icons. Is it possible to specify a vertical desh straight line from the bottom of the canvas to the top of the canvas? or is there any other better ways to do so?

Thanks

**Comment by rrag** [comment] 2017-01-19 10:36
on a discontinuous scale once you know how to convert a date to an integer, you can do it like [here](https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/CandleStickChartWithFullStochasticsIndicator.jsx#L92-L94)

http://rrag.github.io/react-stockcharts/documentation.html#/stochastic_oscillator

pan to see the vertical lines on
2012-03-21
2012-04-19
2012-06-01

anotation can only be svg paths right now, you can create a path for a rectangle but the problem is it will be drawing *above* not *below* the candlestick. there is no way to draw it below using annotations

**Comment by rrag** [comment] 2017-01-20 15:08
dupe of https://github.com/rrag/react-stockcharts/issues/171

**Closed by rrag** 2017-01-20 15:08 UTC

**Comment by li-huo** [comment] 2017-01-22 14:28
thanks
